# Generated by Django 3.0.5 on 2020-05-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestObject',
            new_name='TestModel',
        ),
    ]
